version: "2"

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: ros:kinetic-ros-core
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always

  talker:
    image: ros:kinetic-ros-core
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=talker"
    command: stdbuf -o L rostopic pub /chatter std_msgs/String "hello" -r 1
    networks:
      - ros
    restart: always

  waypoint-planner:
    image: waypoint-planner
    container_name: waypoint_planner
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=waypoint_planner"
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - "XAUTHORITY=/tmp/.docker.xauth"
    command:
      [
        "bash",
        "-c",
        "source /root/home/catkin_ws/devel/setup.bash ; roslaunch waypoint_planner waypoint_planner_headless.launch",
      ]
    networks:
      - ros
    restart: always
  viz:
    image: osrf/ros:kinetic-desktop-full
    container_name: ros_visualizer
    depends_on:
      - ros-master
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=ros_visualizer"
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    #share your user to the container in order to access your x11
    user: 1000:1000 #adapt as needed!
    volumes:
      #share your x11 socket and permissions to the container
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /home/$USER/docker_for_simulations/:/home/$USER:rw #share your home with write permissions
    command: rosrun rviz rviz -d /home/$USER/waypoint_planner/rviz/rviz_waypoint_planner.cfg.rviz

  ros-rqt:
    image: osrf/ros:kinetic-desktop-full
    container_name: ros_rqt
    depends_on:
      - ros-master
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=ros_rqt"
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
      - "ROS_LOG_DIR=/home/$USER/.ros/log"
    #share your user to the container in order to access your x11
    user: 1000:1000 #adapt as needed!
    volumes:
      #share your x11 socket and permissions to the container
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /home/$USER/docker_for_simulations/:/home/$USER:rw #share your home with write permissions
    command: rqt
